[build]
command = "#"
publish = "./"

[[plugins]]
  package = "."
  [plugins.inputs]  
  	"contexts" = ["production"]
    "verbose" = ""
    "mode" = "standalone"
    "redirect_path" = "./redirect_samples"