[build]
command = "#"
publish = "./"

[[plugins]]
  package = "."
  [plugins.inputs]  
    "production" = "./redirects_production_standalone"
    "config_file" = "./netlify.toml"
    "verbose" = "true"
    "mode" = "standalone"